/* SPDX-License-Identifier: GPL-2.0+ */

#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_ASPEED_ESPI_IC_H_
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_ASPEED_ESPI_IC_H_

/* SW-decoded IRQs for eSPI host HW reset and channel events */
#define ASPEED_ESPI_IC_CTRL_RESET	0
#define ASPEED_ESPI_IC_CHAN_RESET	1
#define ASPEED_ESPI_IC_CTRL_EVENT	2
#define ASPEED_ESPI_IC_PERIF_EVENT	3
#define ASPEED_ESPI_IC_VW_EVENT		4
#define ASPEED_ESPI_IC_OOB_EVENT	5
#define ASPEED_ESPI_IC_FLASH_EVENT	6

#endif
